In [1]:
import numpy as np
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

## clean data

In [2]:
file_name = "train.csv"
df = pd.read_csv(file_name, sep=",")
df

,galactic year,galaxy,existence expectancy index,existence expectancy at birth,Gross income per capita,Income Index,Expected years of education (galactic years),Mean years of education (galactic years),Intergalactic Development Index (IDI),Education Index,...,"Intergalactic Development Index (IDI), female","Intergalactic Development Index (IDI), male",Gender Development Index (GDI),"Intergalactic Development Index (IDI), female, Rank","Intergalactic Development Index (IDI), male, Rank",Adjusted net savings,"Creature Immunodeficiency Disease prevalence, adult (% ages 15-49), total",Private galaxy capital flows (% of GGP),Gender Inequality Index (GII),y
0,990025,Large Magellanic Cloud (LMC),0.628657,63.125200,27109.234310,0.646039,8.240543,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.052590
1,990025,Camelopardalis B,0.818082,81.004994,30166.793958,0.852246,10.671823,4.742470,0.833624,0.467873,...,NaN,NaN,NaN,NaN,NaN,19.177926,NaN,22.785018,NaN,0.059868
2,990025,Virgo I,0.659443,59.570534,8441.707353,0.499762,8.840316,5.583973,0.469110,0.363837,...,NaN,NaN,NaN,NaN,NaN,21.151265,6.534020,NaN,NaN,0.050449
3,990025,UGC 8651 (DDO 181),0.555862,52.333293,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.912194,NaN,NaN,0.049394
4,990025,Tucana Dwarf,0.991196,81.802464,81033.956906,1.131163,13.800672,13.188907,0.910341,0.918353,...,NaN,NaN,NaN,NaN,NaN,NaN,5.611753,NaN,NaN,0.154247
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3860,1015056,Columba I,1.029704,82.832063,34310.471408,0.855094,18.578586,10.557143,0.906573,0.862826,...,0.943410,0.902237,1.060532,124.564121,143.907576,26.438719,3.023709,29.294865,0.580785,0.042324
3861,1015056,"Leo II Dwarf (Leo B, DDO 93)",0.937869,75.877098,36899.067719,0.929494,16.153857,9.151665,0.865822,0.747577,...,0.915225,0.798083,1.055118,163.664516,184.291155,20.637654,4.470596,31.085400,0.517558,0.036725
3862,1015056,Canes Venatici I Dwarf,1.036144,93.540275,37002.977875,1.085245,21.066473,16.661344,0.983835,1.100779,...,1.097208,1.044890,1.114754,66.498714,112.887035,28.154859,5.193997,32.145570,0.363862,0.166271
3863,1015056,KKs 3,0.939034,78.274427,28180.459770,0.687655,9.388911,8.908748,0.735694,0.602703,...,0.596164,0.754729,0.825864,182.249079,175.408953,38.963157,2.854140,27.227179,0.711878,0.024187
3864,1015056,NGC 5237,1.032244,91.641356,73109.215949,1.207746,18.910920,16.202486,1.171634,1.085080,...,1.018083,1.099254,1.032783,57.204155,75.434029,23.337587,NaN,29.957851,0.583706,0.100069

In [3]:
#Target :  
Y = df.y
Y
#Features :  
X = df
X=X.drop(['y'], axis=1)
train_X, valid_X, train_Y, valid_Y = train_test_split( X, Y, test_size=1/7.0, random_state=0)

In [4]:
# Get list of categorical variables
s = (train_X.dtypes == 'object')
object_cols = list(s[s].index)
# Make copy to avoid changing original data 
label_X_train = train_X.copy()
label_X_valid = valid_X.copy()

# Apply label encoder to each column with categorical data
label_encoder = LabelEncoder()
for col in object_cols:
    label_X_train[col] = label_encoder.fit_transform(train_X[col])
    label_X_valid[col] = label_encoder.transform(valid_X[col])

print("MAE from Approach 2 (Label Encoding):")

MAE from Approach 2 (Label Encoding):

In [5]:
#Missing values  :
# Imputation
my_imputer = SimpleImputer()
imputed_X_train = pd.DataFrame(my_imputer.fit_transform(label_X_train))
imputed_X_valid = pd.DataFrame(my_imputer.transform(label_X_valid))

# Imputation removed column names; put them back
imputed_X_train.columns = label_X_train.columns
imputed_X_valid.columns = label_X_valid.columns

In [6]:
imputed_X_train

,galactic year,galaxy,existence expectancy index,existence expectancy at birth,Gross income per capita,Income Index,Expected years of education (galactic years),Mean years of education (galactic years),Intergalactic Development Index (IDI),Education Index,...,Current health expenditure (% of GGP),"Intergalactic Development Index (IDI), female","Intergalactic Development Index (IDI), male",Gender Development Index (GDI),"Intergalactic Development Index (IDI), female, Rank","Intergalactic Development Index (IDI), male, Rank",Adjusted net savings,"Creature Immunodeficiency Disease prevalence, adult (% ages 15-49), total",Private galaxy capital flows (% of GGP),Gender Inequality Index (GII)
0,1004004.0,140.0,0.835113,75.693157,23513.133471,0.639134,10.277280,5.472530,0.592335,0.466071,...,8.822368,0.820855,0.841515,1.007858,122.766625,121.388854,21.098124,6.444736,22.81511,0.601519
1,998001.0,141.0,0.780793,76.071147,19420.030542,0.728752,11.806039,13.067858,0.798259,0.838315,...,8.822368,0.820855,0.841515,1.007858,122.766625,121.388854,21.098124,6.444736,22.81511,0.601519
2,1006009.0,115.0,1.106832,87.228708,43842.485552,0.981705,17.992896,15.437622,0.983730,0.894839,...,8.822368,0.820855,0.841515,1.007858,122.766625,121.388854,21.098124,6.444736,22.81511,0.601519
3,1002001.0,50.0,0.658841,60.481936,14245.104533,0.423997,7.806964,6.674971,0.531932,0.379987,...,8.822368,0.820855,0.841515,1.007858,122.766625,121.388854,21.098124,6.444736,22.81511,0.601519
4,994009.0,143.0,0.969656,80.247295,32797.631155,0.880244,13.299290,10.395102,0.819968,0.729852,...,8.822368,0.820855,0.841515,1.007858,122.766625,121.388854,21.098124,6.444736,22.81511,0.601519
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3307,994009.0,88.0,0.892064,74.929243,33126.209386,0.878952,14.706010,12.275761,0.803565,0.746170,...,8.822368,0.820855,0.841515,1.007858,122.766625,121.388854,21.098124,6.444736,22.81511,0.601519
3308,1009020.0,110.0,0.810048,75.313797,10860.308329,0.738090,11.944133,9.904523,0.697288,0.681526,...,8.822368,0.820855,0.841515,1.007858,122.766625,121.388854,21.098124,6.444736,22.81511,0.601519
3309,999000.0,46.0,0.876733,70.317655,19159.869422,0.936359,16.568748,10.242512,0.851355,0.940706,...,8.822368,0.820855,0.841515,1.007858,122.766625,121.388854,21.098124,6.444736,22.81511,0.601519
3310,1004004.0,136.0,0.777020,69.466024,19654.549144,0.638608,11.210961,7.312759,0.670469,0.617849,...,8.822368,0.820855,0.841515,1.007858,122.766625,121.388854,21.098124,6.444736,22.81511,0.601519
3311,1005006.0,72.0,0.900174,85.544583,31273.757758,0.841501,14.328413,8.477916,0.821316,0.673971,...,5.593889,0.751495,0.735128,1.061381,122.766625,121.388854,21.098124,3.368058,22.81511,0.601519

## PCA analysis

In [7]:
scaler = StandardScaler()
# Fit on training set only.
scaler.fit(imputed_X_train)
# Apply transform to both the training set and the test set.
train_X = scaler.transform(imputed_X_train)
test_X = scaler.transform(imputed_X_valid)

In [8]:
# Make an instance of the Model
pca = PCA(.95)
imputed_X_train=pca.fit_transform(imputed_X_train)

In [9]:
pca.n_components_

3

In [10]:
imputed_X_valid=pca.transform(imputed_X_valid)
imputed_X_valid

array([[-2.85509684e+01, -6.31198063e+03, -5.13723467e+03],
       [ 5.79620913e+00, -1.65091935e+02, -8.70775406e+01],
       [-2.36689893e+01, -9.15429266e+03, -7.32235129e+03],
       ...,
       [ 9.87220137e+00, -1.21755395e+03, -8.79861860e+02],
       [-3.58735951e+03, -1.73857817e+04,  1.46414977e+04],
       [-2.39007079e+04,  3.95094491e+02,  1.47043257e+04]])

## Multiple regression analysis

In [11]:
from sklearn import linear_model
regr = linear_model.LinearRegression()
regr.fit(imputed_X_train, train_Y)
print(regr.coef_)

[-3.40719314e-09  1.45484966e-06  3.78500507e-07]

In [12]:
r_sq = regr.score(imputed_X_valid, valid_Y)
print('coefficient of determination:', r_sq)

coefficient of determination: 0.31271970669309646

## predict y for test.csv

In [13]:
file_name = "test.csv"
test_df = pd.read_csv(file_name, sep=",")
test_df

,galactic year,galaxy,existence expectancy index,existence expectancy at birth,Gross income per capita,Income Index,Expected years of education (galactic years),Mean years of education (galactic years),Intergalactic Development Index (IDI),Education Index,...,Current health expenditure (% of GGP),"Intergalactic Development Index (IDI), female","Intergalactic Development Index (IDI), male",Gender Development Index (GDI),"Intergalactic Development Index (IDI), female, Rank","Intergalactic Development Index (IDI), male, Rank",Adjusted net savings,"Creature Immunodeficiency Disease prevalence, adult (% ages 15-49), total",Private galaxy capital flows (% of GGP),Gender Inequality Index (GII)
0,1007012,KK98 77,0.456086,51.562543,12236.576447,0.593325,10.414164,10.699072,0.547114,0.556267,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1007012,Reticulum III,0.529835,57.228262,3431.883825,0.675407,7.239485,5.311122,0.497688,0.409969,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1008016,Reticulum III,0.560976,59.379539,27562.914252,0.594624,11.774890,5.937797,0.544744,0.486167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1007012,Segue 1,0.565910,59.952390,20352.232905,0.837700,11.613621,10.067882,0.691641,0.523441,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1013042,Virgo I,0.588274,55.428320,23959.704016,0.520579,10.392416,6.374637,0.530676,0.580418,...,7.357729,0.583373,0.600445,0.856158,206.674424,224.104054,NaN,7.687626,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,1016064,ESO 383-087 (ISG 39),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
886,1016064,NGC 247,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
887,1016064,ESO 325-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
888,1016064,ESO 540-032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
889,1016064,KK98 77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
#clean dataset from categoral and missing values 
label_test = test_df.copy()
# Apply label encoder to each column with categorical data
label_encoder = LabelEncoder()
for col in object_cols:
    label_test[col] = label_encoder.fit_transform(label_test[col])

In [15]:
# Imputation
my_imputer = SimpleImputer()
imputed_X_test = pd.DataFrame(my_imputer.fit_transform(label_test))
# Imputation removed column names; put them back
imputed_X_test.columns = label_test.columns

In [18]:
#apply pca
imputed_X_test=pca.transform(imputed_X_test)

In [19]:
y_pred = regr.predict(imputed_X_test)

In [20]:
y_pred

array([0.05694436, 0.044915  , 0.07793597, 0.06803236, 0.06077348,
       0.04380271, 0.04637816, 0.05453383, 0.07389003, 0.06857865,
       0.05853178, 0.04709451, 0.05415073, 0.06780119, 0.04786932,
       0.05164167, 0.02806816, 0.05940687, 0.07230804, 0.07295003,
       0.05084664, 0.04692483, 0.07273488, 0.04838495, 0.08291291,
       0.06246109, 0.04789355, 0.07515966, 0.0812487 , 0.04971282,
       0.0499577 , 0.05976229, 0.07034276, 0.07264748, 0.0535303 ,
       0.07563984, 0.06764946, 0.03947322, 0.06072243, 0.05554875,
       0.06517397, 0.05010934, 0.05085739, 0.06904638, 0.08198584,
       0.05398426, 0.06876617, 0.05015272, 0.05510969, 0.10950919,
       0.06432866, 0.06690691, 0.05679   , 0.07828541, 0.04383198,
       0.07577019, 0.04512519, 0.04768164, 0.04781709, 0.07680654,
       0.04767485, 0.06941148, 0.0602652 , 0.06232578, 0.04963136,
       0.0493056 , 0.06431965, 0.05755031, 0.0620394 , 0.07398771,
       0.06794109, 0.03470229, 0.0409907 , 0.04903317, 0.07390712,
       0.07954085, 0.05132794, 0.07336241, 0.04209862, 0.04824178,
       0.0708987 , 0.07164172, 0.06506175, 0.04900904, 0.05674334,
       0.04410983, 0.07182522, 0.06394612, 0.07554152, 0.07322555,
       0.07579062, 0.03192535, 0.04643964, 0.05780198, 0.06436494,
       0.04833198, 0.05574491, 0.03061044, 0.04765259, 0.06163132,
       0.06310761, 0.05546516, 0.06313076, 0.07762803, 0.06458383,
       0.06696397, 0.0573588 , 0.05602781, 0.06858062, 0.06125964,
       0.06709524, 0.05201067, 0.05657349, 0.06350997, 0.05705921,
       0.05402382, 0.05879446, 0.04413604, 0.05715434, 0.05680417,
       0.05023982, 0.05375751, 0.06663406, 0.06232078, 0.0451247 ,
       0.0675135 , 0.03605238, 0.07513144, 0.06147954, 0.095212  ,
       0.04108007, 0.05961142, 0.08275621, 0.03125443, 0.06529047,
       0.05216983, 0.04009616, 0.06333907, 0.06486122, 0.06656753,
       0.06485529, 0.06639536, 0.06558245, 0.06050758, 0.06655322,
       0.07110235, 0.07819077, 0.05101587, 0.05617262, 0.04530353,
       0.05144004, 0.09627678, 0.07014496, 0.06612364, 0.06105695,
       0.04773899, 0.06089345, 0.0544944 , 0.06542874, 0.07194916,
       0.05847148, 0.07027253, 0.0572046 , 0.05295196, 0.04996525,
       0.05132765, 0.07271979, 0.04116882, 0.08155211, 0.05346564,
       0.06608819, 0.07385616, 0.06447178, 0.05884018, 0.06749773,
       0.05384124, 0.07635765, 0.06424973, 0.06638615, 0.06546243,
       0.0602322 , 0.0486217 , 0.04732689, 0.07808906, 0.07272164,
       0.05847457, 0.05843817, 0.06041178, 0.06289088, 0.06863933,
       0.04653728, 0.04022708, 0.06153298, 0.07142354, 0.06092555,
       0.07644526, 0.06344976, 0.04902003, 0.05539193, 0.09368279,
       0.07463386, 0.06537811, 0.0409759 , 0.01689838, 0.06250638,
       0.04638136, 0.0582114 , 0.07119992, 0.05021277, 0.04064318,
       0.0619792 , 0.08673012, 0.08782387, 0.03109412, 0.05758877,
       0.1012119 , 0.06685162, 0.07772718, 0.09658048, 0.07443676,
       0.05748388, 0.05981038, 0.04784243, 0.06521374, 0.07723879,
       0.07094726, 0.05479723, 0.05546276, 0.02837298, 0.04687828,
       0.07775399, 0.05169376, 0.08578726, 0.0695674 , 0.05248815,
       0.04152791, 0.05014321, 0.06220674, 0.07329517, 0.05786305,
       0.06591024, 0.06106132, 0.0722285 , 0.09043275, 0.05706831,
       0.0499721 , 0.06095115, 0.04928588, 0.08562779, 0.06928561,
       0.03821413, 0.04994617, 0.04317504, 0.06364521, 0.06555563,
       0.04853301, 0.07250253, 0.05211701, 0.06929335, 0.06489503,
       0.05726516, 0.06539679, 0.08955231, 0.07059683, 0.06072589,
       0.07204523, 0.08306869, 0.04993904, 0.04057177, 0.04711373,
       0.07036349, 0.09158705, 0.06101292, 0.07388308, 0.09201206,
       0.09188471, 0.05589118, 0.06592455, 0.08650299, 0.07074632,
       0.06191536, 0.06023714, 0.05577274, 0.0664561 , 0.04648292,
       0.10509243, 0.06798692, 0.06517504, 0.07593317, 0.07633074,
       0.06929673, 0.07260934, 0.06909634, 0.05435266, 0.08485286,
       0.08322588, 0.06035375, 0.05667022, 0.05754719, 0.06271234,
       0.07487358, 0.06969172, 0.06099292, 0.06945134, 0.06310256,
       0.07523796, 0.11928161, 0.06214109, 0.10808906, 0.06992161,
       0.05356304, 0.07296677, 0.05486249, 0.06686298, 0.05631611,
       0.05447852, 0.07243813, 0.06144172, 0.07676619, 0.07231172,
       0.08459439, 0.0749181 , 0.0632388 , 0.05486918, 0.07482558,
       0.08605778, 0.06295363, 0.05694138, 0.07580077, 0.08787512,
       0.0560563 , 0.07738145, 0.09131956, 0.06494409, 0.06025323,
       0.06218194, 0.07123165, 0.06663374, 0.05080283, 0.09367815,
       0.17716842, 0.07792377, 0.05824248, 0.05861029, 0.0546134 ,
       0.06740196, 0.04077617, 0.05566683, 0.05458809, 0.09587629,
       0.06571673, 0.07263149, 0.08352272, 0.09368621, 0.05744369,
       0.07840923, 0.10215751, 0.04714805, 0.05669999, 0.08993318,
       0.07430114, 0.0651099 , 0.06200473, 0.0547233 , 0.05647203,
       0.05340927, 0.09353495, 0.08006837, 0.07622802, 0.09259896,
       0.07115524, 0.06327799, 0.06001632, 0.06612895, 0.12428464,
       0.07535918, 0.06364235, 0.0800496 , 0.06326416, 0.13286698,
       0.08390669, 0.08897963, 0.08469413, 0.05631146, 0.04954333,
       0.06174425, 0.04849551, 0.07305485, 0.09651088, 0.04891908,
       0.09543643, 0.0803955 , 0.0848072 , 0.0746328 , 0.06527377,
       0.0509444 , 0.05363547, 0.07684501, 0.05832708, 0.06491172,
       0.06702846, 0.05226318, 0.05941603, 0.08308857, 0.07427395,
       0.05651907, 0.16198229, 0.08372783, 0.06258574, 0.08736123,
       0.08271549, 0.06776524, 0.04816081, 0.10372607, 0.06130466,
       0.08564599, 0.09242131, 0.14606041, 0.08235645, 0.07007994,
       0.1242893 , 0.04914101, 0.0612172 , 0.06309338, 0.06994505,
       0.0690357 , 0.05377369, 0.0492344 , 0.07636095, 0.1834627 ,
       0.3284137 , 0.07101571, 0.25564345, 0.07183368, 0.05421015,
       0.05434273, 0.07671662, 0.07447533, 0.06323699, 0.09874763,
       0.0707133 , 0.09624631, 0.08050566, 0.07956233, 0.10632237,
       0.08275711, 0.06893901, 0.09273564, 0.2234169 , 0.0428903 ,
       0.07751163, 0.06889902, 0.10983738, 0.09358454, 0.08511374,
       0.08835125, 0.05264738, 0.08305364, 0.05029053, 0.0792813 ,
       0.11182546, 0.09828451, 0.06947193, 0.10023809, 0.1505178 ,
       0.0749894 , 0.06491665, 0.05265347, 0.06410591, 0.08975007,
       0.06542095, 0.05322612, 0.07840353, 0.07177379, 0.0829605 ,
       0.08701849, 0.09469361, 0.08063099, 0.05816349, 0.06042603,
       0.08620287, 0.06785087, 0.0707498 , 0.10269309, 0.06325752,
       0.0974089 , 0.07911991, 0.13676753, 0.10765541, 0.09390066,
       0.10454071, 0.05744935, 0.12866508, 0.10107363, 0.05084156,
       0.07798145, 0.10315482, 0.21876436, 0.0596065 , 0.08748137,
       0.09641468, 0.09446127, 0.06997676, 0.08302117, 0.22258293,
       0.09189605, 0.06113624, 0.06583871, 0.09334453, 0.07363149,
       0.07412926, 0.09860522, 0.08219551, 0.07013501, 0.16719501,
       0.0785314 , 0.06185986, 0.06965338, 0.1120374 , 0.05985515,
       0.0863918 , 0.0753327 , 0.05976605, 0.07738623, 0.06803058,
       0.11476522, 0.1015777 , 0.09002397, 0.12962016, 0.09600623,
       0.05789662, 0.06923046, 0.06773595, 0.09242483, 0.07055874,
       0.10818214, 0.07448945, 0.07261001, 0.06854505, 0.06524845,
       0.17963209, 0.10654289, 0.08374378, 0.07368966, 0.07272692,
       0.10010559, 0.08244583, 0.19548037, 0.07867998, 0.05304151,
       0.08579532, 0.08530202, 0.08105613, 0.05242716, 0.08959039,
       0.09986693, 0.08196054, 0.13399791, 0.05509499, 0.1008755 ,
       0.07546112, 0.1126744 , 0.1695931 , 0.08747831, 0.07524705,
       0.08265931, 0.1160695 , 0.07072733, 0.14390024, 0.10647023,
       0.07139069, 0.06981914, 0.08891435, 0.0564383 , 0.09690083,
       0.06275263, 0.04972628, 0.09068709, 0.03972005, 0.08776668,
       0.06498227, 0.07767038, 0.10049137, 0.15100642, 0.23157066,
       0.04947146, 0.12286333, 0.06065824, 0.08194842, 0.10926635,
       0.06430107, 0.09839186, 0.08725517, 0.05542243, 0.12005066,
       0.06085265, 0.06543887, 0.08149655, 0.08533773, 0.07616481,
       0.14523748, 0.08110416, 0.06891397, 0.05098678, 0.08760184,
       0.15255629, 0.12720062, 0.07732159, 0.08584705, 0.06016853,
       0.09375703, 0.10419991, 0.0798493 , 0.08383112, 0.08823333,
       0.09003423, 0.12692533, 0.059927  , 0.23615477, 0.11580236,
       0.11782712, 0.06678623, 0.08957028, 0.0699853 , 0.08497343,
       0.06733963, 0.08985935, 0.08234757, 0.07881661, 0.08989237,
       0.11300141, 0.09104923, 0.06897662, 0.07415481, 0.08589985,
       0.08311705, 0.08218617, 0.06841394, 0.06679148, 0.10181692,
       0.09462039, 0.08719299, 0.0517723 , 0.10188748, 0.06242433,
       0.07768641, 0.16919302, 0.07783385, 0.07207089, 0.08524775,
       0.06737356, 0.12887611, 0.09404967, 0.1349276 , 0.2231434 ,
       0.05674482, 0.08889808, 0.08876174, 0.23877992, 0.11829971,
       0.123031  , 0.12525801, 0.05472783, 0.15229573, 0.07212408,
       0.07012893, 0.18943515, 0.10887024, 0.07246885, 0.07346701,
       0.06445935, 0.09100737, 0.07076036, 0.06495403, 0.06888425,
       0.14634764, 0.10323648, 0.08511942, 0.0970199 , 0.22345735,
       0.07479847, 0.08700273, 0.0958138 , 0.16473377, 0.12636946,
       0.07772867, 0.0802044 , 0.09919236, 0.08632331, 0.08797283,
       0.05717559, 0.08818491, 0.0714003 , 0.14953912, 0.06709107,
       0.07577496, 0.08822809, 0.11428092, 0.06114516, 0.15846017,
       0.08540262, 0.12262701, 0.11428035, 0.11644011, 0.07784525,
       0.16291506, 0.06922389, 0.10007094, 0.1120408 , 0.12690964,
       0.10149186, 0.1184458 , 0.08561766, 0.08919324, 0.14983805,
       0.11885097, 0.07673843, 0.07178253, 0.05862367, 0.09360738,
       0.07271692, 0.24123742, 0.07936753, 0.0945836 , 0.09263276,
       0.11947924, 0.09057654, 0.24345136, 0.18745779, 0.09864558,
       0.15318605, 0.06588205, 0.12534428, 0.0784513 , 0.22871613,
       0.08737932, 0.07203462, 0.10312599, 0.1282842 , 0.11693341,
       0.14264031, 0.10314135, 0.06521074, 0.10608599, 0.12908897,
       0.10870183, 0.17973644, 0.13164822, 0.09732219, 0.13496574,
       0.12270221, 0.13568459, 0.11235174, 0.09025958, 0.07568904,
       0.10558981, 0.11491874, 0.10307882, 0.08181809, 0.13697586,
       0.14758417, 0.063459  , 0.11519526, 0.12544085, 0.12033314,
       0.12763409, 0.0640014 , 0.08901312, 0.1263353 , 0.11418962,
       0.12992058, 0.14156267, 0.15298881, 0.09523167, 0.11626517,
       0.08696729, 0.07301395, 0.10728929, 0.08169193, 0.14781596,
       0.11883894, 0.14609269, 0.12658315, 0.16600803, 0.06395687,
       0.0952117 , 0.17031228, 0.11951083, 0.11853417, 0.11507698,
       0.06958691, 0.11501191, 0.13221436, 0.10266325, 0.12843666,
       0.09642099, 0.11980873, 0.13660864, 0.1246262 , 0.22756945,
       0.15133163, 0.15473758, 0.10572013, 0.07426608, 0.14029676,
       0.11558427, 0.12929703, 0.14210229, 0.23403304, 0.11799625,
       0.08983625, 0.09990693, 0.15074413, 0.09998101, 0.13701199,
       0.13882183, 0.07267852, 0.13857274, 0.08466539, 0.15048522,
       0.10480183, 0.20151599, 0.13046686, 0.13668119, 0.11341083,
       0.13756477, 0.14335493, 0.16532766, 0.15719644, 0.12043341,
       0.15965881, 0.11105364, 0.12967661, 0.08897807, 0.10947582,
       0.1292963 , 0.14675648, 0.18988152, 0.29154021, 0.13304459,
       0.12326147, 0.13979095, 0.1117707 , 0.12422646, 0.2489274 ,
       0.12837751, 0.16042853, 0.11601286, 0.09285723, 0.13841709,
       0.13470754, 0.1574438 , 0.19909607, 0.17085944, 0.15263071,
       0.10570717, 0.09092212, 0.11995396, 0.13194146, 0.14186749,
       0.15783462, 0.1463924 , 0.12224859, 0.11957785, 0.10788066,
       0.15438728, 0.08497895, 0.13131286, 0.15654657, 0.15205594,
       0.13972183, 0.13663119, 0.10576607, 0.14697539, 0.21060751,
       0.11380009, 0.14425487, 0.14189282, 0.12125967, 0.12886097,
       0.13678072, 0.12499541, 0.11266026, 0.22109058, 0.13168187,
       0.08667854, 0.08667856, 0.08667854, 0.08667854, 0.08667855])